# Encoder / Decoder / Discriminator architecture.
conv2:
  block: 'skip'      # 'skip' or 'relu'
  layers_CE: 3       # Conv2Encoder layers
  layers_EM: 4       # WatermarkEmbedder layers
  hidden_dim: 64
